# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      working-directory: ./
      id: compose
      run: docker-compose -f "docker-compose.yml" up 
      
    - name: Output of compose
    working-directory: ./
    run: echo "The time was ${{ steps.compose.outputs.data }}"

    - name: Stop containers
      working-directory: ./
      if: always()
      run: docker-compose -f "docker-compose.yml" down
